# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant file for libvirt/kvm provider

Vagrant.configure(2) do |config|
  config.vm.box = "atomicapp/dev"
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 1048
  end

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 1024
  end

end

