= Contributing to ADB

The following is a set of guidelines for contributing to ADB, which is
hosted in the https://github.com/projectatomic[Project Atomic
Organization] on GitHub. These are just guidelines, please use your best
judgment and feel free to propose changes to this document in a pull
request.

At this point, this document is not complete, but as decisions are made
on
https://www.redhat.com/mailman/listinfo/container-tools[container-tools@redhat.com]
ML they will be added to this document.

[[pull-requests]]
== Pull Requests

* All changes should be made by pull request (PR), even from core
committers/maintainers.

* All changes need 2 ACKs from maintainers before they will be approved
for inclusion. If the author of the PR is a maintainer, the submission
is considered 1 of the 2 ACKs. Therefore PRs from maintainers only
require one additional ACK. By "2 ACKs" we mean that 2 maintainers must
acknowledge that the change is a good one. The 2nd person to ACK the PR
should merge the PR with a comment including their agreement.
