# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Example configuration of new VM..
  config.vm.define :vagrant_rhel do |vagrant_host|
    # Box name
    vagrant_host.vm.box = 'rhel-7.0'
    vagrant_host.vm.hostname = "vagrant-test"

    config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [ ".git/", ".#*", "*~" ]

    vagrant_host.vm.provision 'shell', inline: "sudo subscription-manager repos --enable rhel-7-server-extras-rpms"
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y install bash-completion bind-utils setroubleshoot python-pip system-storage-manager"
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y groupinstall 'Development Tools'"
    vagrant_host.vm.provision 'shell', inline: "sudo yum -y install docker"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl stop docker > /dev/null 2>&1 || :" #in case this isn't first run
    vagrant_host.vm.provision 'shell', inline: "sudo groupadd docker > /dev/null 2>&1 || : "
    vagrant_host.vm.provision 'shell', inline: "sudo usermod -a -G docker vagrant"
    vagrant_host.vm.provision 'shell', inline: "sudo systemctl enable docker && sudo systemctl start docker"
    vagrant_host.vm.provision 'shell', inline: "sudo chown root:docker /var/run/docker.sock"

  end
end
