= Vagrantfile: CentOS Single-Node Mesos Marathon
:toc:

This Vagrantfile sets up ADB for development with Mesos and Marathon. It
also sets up private networking that will be used to expose the services
to the host. This Vagrantfile is based on
https://atlas.hashicorp.com/projectatomic/boxes/adb[ADB] vagrant box. It
sets up Mesos master & slave and Marathon on a CentOS 7 system. It uses
the rpm packages for these from
http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm[Mesosphere
repo].

[[quickstart]]
== Quickstart

To setup a virtualization provider or to install Vagrant refer to the
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.adoc[ADB installation
instructions].

To bring up a Vagrant box using a different virtualization provider,
replace `libvirt` in the following command with the provider of your choice.

....
$ sudo vagrant up --provider=libvirt
....

[NOTE]
====
The Vagrantfile for this setup has an embedded
http://www.ansible.com/[Ansible] playbook that will take care of most of
the provisioning. Depending on your Internet connection, the box should
be up and running with all the necessary packages installed within a few
minutes to about an hour.
====

Once the box is up, you can access Mesos master UI on
http://10.2.2.2:5050[10.2.2.2:5050] and Marathon UI on
http://10.2.2.2:8080[10.2.2.2:8080] if you've not changed the value of
the parameter *ip* in Vagrantfile.
