= Vagrantfile: OpenShift Origin
:toc:

This Vagrantfile:

* Sets up ADB for development with OpenShift
* Sets up private networking that is used to expose various services to
the host
* Provisions an instance of http://www.openshift.org//[OpenShift Origin]

If you are interested in the process used in the Vagrantfile to setup
OpenShift, please read the comments at the top of the file.

The Vagrantfile changes after ADB 1.6.0 are not backward compatible. So
if you are using ADB prior to 1.7.0, you can use the
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/v1.6.0/components/centos/centos-openshift-setup/Vagrantfile[old Vagrantfile].

[[quickstart]]
== Quickstart

.  Get the latest ADB box and add it to vagrant as described in the
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.adoc[ADB
installation instructions].

.  Create a directory for the Vagrant Box.
+
----
$ mkdir directory && cd directory
----

.  Download the Vagrantfile.
+
----
$ curl -sL https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-openshift-setup/Vagrantfile > Vagrantfile
----
+
[NOTE]
====
* The ADB OpenShift Vagrant Box IP defaults to `10.1.2.2`. If you want a
different IP then change the `PUBLIC_ADDRESS` variable in the
Vagrantfile.
* If you want to use the latest OpenShift Origin image, then you need to
change the `IMAGE_TAG` variable in the Vagrantfile, to `latest`.
Alternatively, you can specify the value based on the
https://hub.docker.com/r/openshift/origin/tags/[OpenShift Origin
version] you need, for the variable. For instance, `IMAGE_TAG="v1.2.1"`
====

.  Start the Vagrant Box.
+
----
$ vagrant up
----

.  Proceed with using ADB as described in link:../../../docs/using.adoc[Using
Atomic Developer Bundle].

[additiona-openshit-config]
== Additional configuration for OpenShift

If you plan to use OpenShift from the host, you may wish to download
`oc` for your platform from an
https://github.com/openshift/origin/releases[OpenShift Origin Release].

You may wish to verify that OpenShift is setup using the `oc` CLI as
follows:

.  Check OpenShift status using `oc`.
+
----
$ oc status
----

.  Check available templates.
+
----
$ oc get templates -n openshift
----

.  Deploy an application using available templates.
+
----
$ oc new-app nodejs-example
----

.  Get route information of different deployed apps.
+
----
$ oc get routes
----
