= Components for Container Development Kit
:toc:

[[what-is-cdk]]
== What is the Red Hat Container Development Kit

Red Hat Container Development Kit (CDK) is a set of tools that helps you
quickly and easily set up an environment for developing and testing
containerized applications on the Red Hat Enterprise Linux platform. Red
Hat CDK is available for Microsoft Windows, Mac OS X, and Linux
operating systems, thus allowing you to use your favorite platform to
produce applications that are ready to deploy in the Red Hat Enterprise
Linux ecosystem.

Red Hat CDK is a part of the Red Hat Developers program, which provides
tools, resources, and support for developers who wish to utilize Red Hat
solutions and products to create applications, both locally and in the
cloud. For additional information and to register to become a part of
the program, visit http://developers.redhat.com[developers.redhat.com].

[[installation-instructions]]
== Installation Instructions

Detailed installation instructions for setting up Red Hat CDK on each of
the supported platforms (Microsoft Windows, Mac OS X, and Linux) are
available in the
https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-installation-guide/[CDK
Installation Guide]

[[getting-started]]
== Getting Started

The
https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-container-development-kit/[Getting
Started Guide] describes the individual components that form Red Hat
CDK, followed by instructions on how to obtain, install, and configure
the components, so that you can start using the resulting environment to
interact with containers and develop containerized applications.

An additional document, the Container Development Guide, will be
published with The GA release of the CDK. This guide contains practical
usage examples, including advanced topics such as developing
multi-container applications and container orchestration using
Kubernetes or OpenShift.

[[updated-releases]]
== Updated Releases

Updated releases of the CDK will be available to download from Red Hat
Developer portal, http://developers.redhat.com under Technologies.
Select http://developers.redhat.com/products/cdk/download/[Red Hat
Container Development Kit] from the list of product variants.

[[feedback-and-questions]]
== Feedback and Questions

Please join the container-tools@redhat.com mailing list to ask questions
and provide feedback.
