= Using Atomic Developer Bundle
:toc:
:toc-placement!:

This document describes how to configure and use ADB and its related plugins.

'''
toc::[]
'''

[[principles]]
== Principles

Consider ADB to be ephemeral and do not store data in it long term. It
is recommended that you do the following:

* Back up your code.
* Use a source control system.
* Mount your code into the box from your host system. The ADB Vagrantfiles
already mount your home directory from the host into ADB using
https://github.com/dustymabe/vagrant-sshfs/[vagrant-sshfs]. Additional
shares can also be defined. Refer to the
link:#vagrant-bi-directional-folder-sync[bi-directional folder sync
section] for more information.

Doing these things is beyond the scope of this document. Consult your
Operating System manuals and the http://vagrantup.com/[Vagrant] website
for more details.

Once you start ADB you can use it as:

* a server resource for host-based tools (Eclipse/CLIs) or
* a Linux virtual machine.

For a quick high level glimpse at ADB and how you can use it refer to
the
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/README.adoc[Readme].
For detailed instructions on how to install ADB refer to the
link:docs/installing.adoc[Installation Document].

[[using-adb-with-host-based-tools-eclipse-and-clis]]
Using ADB with host-based tools (Eclipse and CLIs)
--------------------------------------------------

Many users have preferred development environments built from tools
running on their development workstation. Even if these workstations are
unable to run containers or container-components natively, the user may
still want to use their preferred tools, editors, etc. ADB can be used
with these tools in a way that makes it seamless to interact with files,
preferred development tools, etc.

ADB exposes the docker daemon port and orchestrator access points so
that tools like Eclipse and various CLIs can interact with them. For
security reasons, some ports, such as the docker daemon port, are TLS
protected. Therefore some configuration is required before the service
can be accessed. Vagrant-service-manager makes this configuration simple
by providing easy access to the TLS certificates and the other
environment variables or configuration information.

To use ADB with Host-Based tools:

. Install the vagrant-service-manager plugin. :
+
....
vagrant plugin install vagrant-service-manager
....
+
More information about the vagrant-service-manager plugin is available
in the source repository_.

. Enable the desired service(s) in the ADB Vagrantfile as:
+
....
config.servicemanager.services = 'openshift'
....
+
[NOTE]
====
* Docker is the default service for ADB and does not require any
configuration to ensure it is started. Red Hat Enterprise Linux
Container Development Kit, which is based on Atomic Developer Bundle,
automatically starts OpenShift.
* You can use a comma-separated list to enable multiple services. For
instance: docker, openshift.
====

. Enable the relevant option for the services you have selected in the
Vagrantfile as:
+
For example, specific versions of OpenShift can be specified using the
following variables:
+
* `config.servicemanager.openshift_docker_registry = "docker.io"` -
Specifies the registry from where the service should be pulled.
+
* `config.servicemanager.openshift_image_name = "openshift/origin"` -
Specifies the image to be used.
+
* `config.servicemanager.openshift_image_tag = "v1.2.0"` - Specifies
the version of the image to be used.

.  Start ADB using `vagrant up`. You will find detailed installation
instructions in the link:docs/installing.adoc[Installation document].

.  Configure the environment and download the required TLS certificates
using the plugin. The example below shows the command and the output for
Linux and Mac OS X. On Microsoft Windows the output may vary depending
on the execution environment:
+
....
$ vagrant service-manager env
# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/foo/bar/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
....
+
Setting these environment variables allows programs, such as Eclipse and
the docker CLI to access the docker daemon.
+
[NOTE]
====
When the OpenShift service is running in the VM, a Docker
registry is also started. This Docker registry can be used by external
tools such as Eclipse to push or pull images. The Docker registry URL is
exported as a variable, and can be accessed by running the following
command:
....
$ vagrant service-manager env openshift
# openshift env:
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
export DOCKER_REGISTRY=hub.openshift.centos7-adb.10.1.2.2.xip.io
....
====

.  Begin developing.
+
If you do not have the docker CLI, you can use the `install-cli` command
as:
+
....
$ vagrant service-manager install-cli docker
....
+
However, if you are using the docker CLI, you can just run it from the
command line and it will work as expected.
+
[NOTE]
====
If you encounter a Docker client and server version mismatch such as:
....
$ docker ps
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
....
You will need to download an earlier compatible version of Docker for
your host machine. Docker release versions and docker API versions are
not the same. Typically, you will need to try the previous release (i.e.
if you get this error message using a docker 1.9 CLI, try a docker 1.8
CLI).
====
+

. If you are using Eclipse, you should follow these steps:
..  Install the
http://www.eclipse.org/community/eclipse_newsletter/2015/june/article3.php[Docker
Tooling] plugin.
,.  Enable the three Docker Views (Docker Explorer, Docker Containers,
and Docker Images) by choosing **Windows->Show Views->Others**.
..  Enable the Console by choosing **Windows->Show Views->Console**.
..  In the `Docker Explorer` view, click to add a connection. You should
provide a "connection name". If your Environment Variables are set
correctly, the remaining fields will auto-populate. If not, using the
output from `vagrant service-manager env docker`, put the DOCKER_HOST
variable in the "TCP Connection" field and the DOCKER_CERT_PATH in the
"Authentication Section" Path.
..  You can test the connection and then accept the results. At this
point, you are ready to use ADB with Eclipse.

NOTE: Testing has been done with Eclipse 4.5.0.

[[using-the-box-via-ssh]]
== Using the box via SSH

Today, most users will work inside the Vagrant box. Access the box by
using `ssh` to login to it with the following command:

....
vagrant ssh
....

You are now at a shell prompt inside the Vagrant box. You can now
execute commands and use the tools provided.

You can use the
https://github.com/projectatomic/adb-utils/blob/master/README.adoc[sccli]
to manage the orchestration services inside of ADB. `sccli` makes it
easy to start and stop orchestration providers like Kubernetes or
OpenShift.

[[using-docker]]
=== Using `docker`

ADB provides a full container environment and runs both `docker` and
`kubernetes`. All standard commands work, for example:

....
ADB pull centos
 docker run -t -i centos /bin/bash
....

[[using-atomic-app-and-nulecule]]
=== Using Atomic App and Nulecule

Details on these projects can be found at these URLs:

* Atomic App: https://github.com/projectatomic/atomicapp
* Nulecule: https://github.com/projectatomic/nulecule

The
https://registry.hub.docker.com/u/projectatomic/helloapache/[helloapache]
example can be used to test your installation.

NOTE: Many Nulecule examples expect a working Kubernetes environment.
Use the
link:../components/centos/centos-k8s-singlenode-setup/Vagrantfile[Vagrantfile]
and refer the corresponding
link:../components/centos/centos-k8s-singlenode-setup/README.adoc[README]
to set up a single node Kubernetes environment.

You can verify your environment by executing `kubectl get nodes`. The
expected output is:

....
$ kubectl get nodes
NAME        LABELS                             STATUS
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready
....

[[vagrant-bi-directional-folder-sync]]
== Vagrant bi-directional folder sync

For an introduction into Vagrant's synced folders feature, we recommend
you to start with the corresponding
https://www.vagrantup.com/docs/synced-folders/basic_usage.html[Vagrant
documentation].

Synced folders enable movement of files (such as, code files) between
the host and the Vagrant guest. Apart from the
https://www.vagrantup.com/docs/synced-folders/rsync.html[rsync synced
folder type], synced folder types are usually bi-directional and
continuously sync the folder while the guest is running.

The following synced folder types work out of the box with the ADB
Vagrant box, for both Virtualbox as well as Libvirt/KVM :

* https://github.com/dustymabe/vagrant-sshfs[vagrant-sshfs]: Works with
Linux/GNU, OS X and Microsoft Windows. It is the recommended choice for
enabling synced folders and the
link:#using-custom-vagrantfiles-for-specific-use-cases[custom
Vagrantfile examples] use it per default. In the suggested default
configuration, your home directory on the host (for example,
`/home/john`) is synced to the equivalent path on the guest VM
(`/home/john`). For Windows users, there is a little caveat, their home
directory (for example, C:\Users\john) must be mapped to a Unix style
path (`/c/users/john`).
* https://www.vagrantup.com/docs/synced-folders/nfs.html[NFS]: Works
with Linux/GNU and OS X.

There are also some other alternatives, which are, however, not yet
properly tested with ADB.

* https://www.vagrantup.com/docs/synced-folders/smb.html[SMB]: For
Microsoft Windows.
** You need to install cifs-utils RPM inside ADB, for the SMB synced
folder type to work:
+
....
sudo yum install cifs-utils
....
* https://www.virtualbox.org/manual/ch04.html#sharedfolders[Virtualbox
shared folder]: For Virtualbox users with Virtualbox guest additions.
** At this point of time Virtualbox guest additions do not come
pre-installed in the ADB Vagrant box.
** For installation details, please refer to
https://www.virtualbox.org/manual/ch04.html[Virtualbox documentation].
** You can also use
https://github.com/dotless-de/vagrant-vbguest[vagrant-vbguest] plugin to
install Virtualbox guest additions in ADB Vagrant box.

[[some-useful-commands]]
== Some useful commands

* `vagrant halt` - Stop the vagrant box, temporarily:
+
You can use `vagrant halt` to gracefully stop the vagrant box and
continue with your work when you start next with `vagrant up`. This will
not cause any loss of data. It is recommended to stop the vagrant box
before you shutdown your machine, to save CPU and RAM consumption. Also,
powering off your machine without stopping the vagrant box, could cause
errors when you resume using it.
* `vagrant status` - Check the Status of the Vagrant box:
+
Use `vagrant status` to check the status of ADB and to check which
virtualization provider is being used and the status of the provider.
* `vagrant destroy` - Destroy the Vagrant box:
+
WARNING: Using `vagrant destroy` will destroy any data you stored in
the Vagrant box. You will not be able to restart this instance and will
have to create a new one using `vagrant up`.
